### ISSUE TITLE
Missing licence file

### ISSUE THREAD

**Issue by Gspohu** [yeKcim/inventaire#1]
Hello,

I find your software very interesting, thank you for your work. Could you confirm that the software is under a Free license ? To do this, simply add a file to the root containing the license of your choice.

For the choice of license I recommend the AGPL, which seems the most suitable for your type of software.
https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License
https://www.gnu.org/licenses/agpl-3.0.html

If you confirm that this software is Free, I will install it on my server and I intend to contribute to your project soon.

Good luck for the future,

Valentin
POHU

**Comment by yeKcim** [comment]
done : a5850baa465bc11414ac9ae87360c0800a34f2eb
https://github.com/yeKcim/inventaire/blob/master/LICENSE.txt

**Comment by Gspohu** [comment]
Thank you !
